// generated by newgenasym  Sat Jul 08 16:14:09 2023


module dip4 (\5v , gnd, rxd, txd);
    inout \5v ;
    inout gnd;
    inout rxd;
    inout txd;


    initial
        begin
        end

endmodule
