-- generated by newgenasym Sat Jul 08 16:14:09 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dip4 is
    port (    
	\5v\:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC);
end dip4;
