// generated by newgenasym  Mon Jul 10 16:50:34 2023


module lm7805 (gnd, \input , \output );
    inout gnd;
    inout \input ;
    inout \output ;


    initial
        begin
        end

endmodule
