-- generated by newgenasym Mon Jul 10 16:50:34 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm7805 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC);
end lm7805;
