-- generated by newgenasym Wed Jan 05 10:53:24 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cp is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cp;
