// generated by newgenasym  Thu Jul 06 21:32:53 2023


module adxl345 (\3v3 , \5v , cs, gnd, in1, in2, scl, sda, sdo, vs);
    inout \3v3 ;
    inout \5v ;
    inout cs;
    inout gnd;
    inout in1;
    inout in2;
    inout scl;
    inout sda;
    inout sdo;
    inout vs;


    initial
        begin
        end

endmodule
