-- generated by newgenasym Thu Jul 06 21:32:53 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adxl345 is
    port (    
	\3v3\:     INOUT  STD_LOGIC;    
	\5v\:      INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end adxl345;
