-- generated by newgenasym Sat Jul 08 20:13:42 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1n4377\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \1n4377\;
