-- generated by newgenasym Sat Jul 08 16:13:48 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dip2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end dip2;
