// generated by newgenasym  Thu Jul 06 19:45:36 2023


module \89c52  (\ale/prog* , \ea* , gnd, \p0.0/ad0 , \p0.1/ad1 , \p0.2/ad2 ,
        \p0.3/ad3 , \p0.4/ad4 , \p0.5/ad5 , \p0.6/ad6 , \p0.7/ad7 , \p1.0/t2 ,
        \p1.1/t2ex , \p1.2 , \p1.3 , \p1.4 , \p1.5 , \p1.6 , \p1.7 , \p2.0/a8 ,
        \p2.1/a9 , \p2.2/a10 , \p2.3/a11 , \p2.4/a12 , \p2.5/a13 , \p2.6/a14 ,
        \p2.7/a15 , \p3.0/rxd , \p3.1/txd , \p3.2/int0* , \p3.3/int1* ,
        \p3.4/t0 , \p3.5/t1 , \p3.6/wr* , \p3.7/rd* , \psen* , rst, vcc, xtal1,
        xtal2);
    inout \ale/prog* ;
    inout \ea* ;
    inout gnd;
    inout \p0.0/ad0 ;
    inout \p0.1/ad1 ;
    inout \p0.2/ad2 ;
    inout \p0.3/ad3 ;
    inout \p0.4/ad4 ;
    inout \p0.5/ad5 ;
    inout \p0.6/ad6 ;
    inout \p0.7/ad7 ;
    inout \p1.0/t2 ;
    inout \p1.1/t2ex ;
    inout \p1.2 ;
    inout \p1.3 ;
    inout \p1.4 ;
    inout \p1.5 ;
    inout \p1.6 ;
    inout \p1.7 ;
    inout \p2.0/a8 ;
    inout \p2.1/a9 ;
    inout \p2.2/a10 ;
    inout \p2.3/a11 ;
    inout \p2.4/a12 ;
    inout \p2.5/a13 ;
    inout \p2.6/a14 ;
    inout \p2.7/a15 ;
    inout \p3.0/rxd ;
    inout \p3.1/txd ;
    inout \p3.2/int0* ;
    inout \p3.3/int1* ;
    inout \p3.4/t0 ;
    inout \p3.5/t1 ;
    inout \p3.6/wr* ;
    inout \p3.7/rd* ;
    inout \psen* ;
    inout rst;
    inout vcc;
    inout xtal1;
    inout xtal2;


    initial
        begin
        end

endmodule
