-- generated by newgenasym Thu Jul 06 19:45:36 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \89c52\ is
    port (    
	\ale/prog*\: INOUT  STD_LOGIC;    
	\ea*\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\p0.0/ad0\: INOUT  STD_LOGIC;    
	\p0.1/ad1\: INOUT  STD_LOGIC;    
	\p0.2/ad2\: INOUT  STD_LOGIC;    
	\p0.3/ad3\: INOUT  STD_LOGIC;    
	\p0.4/ad4\: INOUT  STD_LOGIC;    
	\p0.5/ad5\: INOUT  STD_LOGIC;    
	\p0.6/ad6\: INOUT  STD_LOGIC;    
	\p0.7/ad7\: INOUT  STD_LOGIC;    
	\p1.0/t2\: INOUT  STD_LOGIC;    
	\p1.1/t2ex\: INOUT  STD_LOGIC;    
	\p1.2\:    INOUT  STD_LOGIC;    
	\p1.3\:    INOUT  STD_LOGIC;    
	\p1.4\:    INOUT  STD_LOGIC;    
	\p1.5\:    INOUT  STD_LOGIC;    
	\p1.6\:    INOUT  STD_LOGIC;    
	\p1.7\:    INOUT  STD_LOGIC;    
	\p2.0/a8\: INOUT  STD_LOGIC;    
	\p2.1/a9\: INOUT  STD_LOGIC;    
	\p2.2/a10\: INOUT  STD_LOGIC;    
	\p2.3/a11\: INOUT  STD_LOGIC;    
	\p2.4/a12\: INOUT  STD_LOGIC;    
	\p2.5/a13\: INOUT  STD_LOGIC;    
	\p2.6/a14\: INOUT  STD_LOGIC;    
	\p2.7/a15\: INOUT  STD_LOGIC;    
	\p3.0/rxd\: INOUT  STD_LOGIC;    
	\p3.1/txd\: INOUT  STD_LOGIC;    
	\p3.2/int0*\: INOUT  STD_LOGIC;    
	\p3.3/int1*\: INOUT  STD_LOGIC;    
	\p3.4/t0\: INOUT  STD_LOGIC;    
	\p3.5/t1\: INOUT  STD_LOGIC;    
	\p3.6/wr*\: INOUT  STD_LOGIC;    
	\p3.7/rd*\: INOUT  STD_LOGIC;    
	\psen*\:   INOUT  STD_LOGIC;    
	RST:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	XTAL1:     INOUT  STD_LOGIC;    
	XTAL2:     INOUT  STD_LOGIC);
end \89c52\;
