// generated by newgenasym  Thu Jul 06 17:13:42 2023


module oled (cs, dc, gnd, res, scx, sda, vdd);
    inout cs;
    inout dc;
    inout gnd;
    inout res;
    inout scx;
    inout sda;
    inout vdd;


    initial
        begin
        end

endmodule
