-- generated by newgenasym Thu Jul 06 17:13:42 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity oled is
    port (    
	CS:        INOUT  STD_LOGIC;    
	DC:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	SCX:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end oled;
