-- generated by newgenasym Wed Dec 08 13:32:10 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC);
end crystal;
