-- generated by newgenasym Fri Apr 08 16:45:29 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity buzzer is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end buzzer;
