-- generated by newgenasym Sat Jul 08 20:15:31 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end led;
