-- generated by newgenasym Sat Jul 08 20:16:44 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resistor is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end resistor;
